DROP DATABASE IF EXISTS quiz;

CREATE DATABASE IF NOT EXISTS quiz default charset utf8 COLLATE utf8_bin;

GRANT ALL PRIVILEGES ON *.* TO 'quiz'@'localhost' IDENTIFIED BY 'quiz' WITH GRANT OPTION;

use quiz;

CREATE TABLE tb_question (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
  title VARCHAR(255) NOT NULL COMMENT '标题',
  content TEXT COMMENT '内容',
  answer VARCHAR(1) NOT NULL DEFAULT 'A' COMMENT '答案:A B C D',
  note TEXT COMMENT '题目分析',
  c_time TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '创建时间',
  status TINYINT(1) NOT NULL DEFAULT 0 COMMENT '状态:0:启用 1：弃用',
  PRIMARY KEY (id)
) ENGINE InnoDB DEFAULT CHARSET=utf8 COMMENT '题库';